liip_imagine:
    driver: "gd"
    filter_sets:
        img: #nom de filtre
           quality: 75
           filters:
               thumbnail: { size: [120, 90], mode: outbound }
        echelle:
            quality: 85
            filters:
                scale:
                    dim: [250,250]
